services:
- type: web
  name: n8n
  runtime: docker
  repo: https://github.com/TahaTahir45/n8n-deploy
  branch: main
  plan: free
  envVars:
  - key: WEBHOOK_TUNNEL_URL
    value: "https://fuelprice.onrender.com/"
  - key: N8N_BASIC_AUTH_USER
    value: "admin"
  - key: N8N_BASIC_AUTH_PASSWORD
    value: "fuel123"
  - key: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - key: N8N_PORT
    value: "5678"
  - key: N8N_HOST
    value: "0.0.0.0"
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
