services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        value: 'fuelprice'
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 'secret123'
      - key: WEBHOOK_TUNNEL_URL
        value: 'https://fuelprice.onrender.com'
